config/routes.rb
Rails.application.routes.draw do

  
  resources :users, only: [:index, :show, :new, :edit, :create, :update]
  resources :sessions, only: [:new, :create, :destroy]

  match 'signup', to: 'users#new', via: 'get'
  match 'signin', to: 'sessions#new', via: 'get'
  match 'signout', to: 'sessions#destroy', via: 'delete'

  root 'sessions#new'
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { email.downcase! }
  
  enum sex: { man: "1", woman: "2" }

  has_secure_password
  mount_uploader :image, ImageUploader

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  
end

app/controllers/post_controller.rb
class PostController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :signed_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:nickname, :email, :age, :sex, :image, :remember_digest, :password, :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to root_url unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in?
    !current_user.nil?
  end

  def signed_in_user
    redirect_to signin_url unless signed_in?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<div class="header">
  <div class="headerlogo">
    <%=image_tag "1_Primary_logo_on_transparent_379x63.png"%>
  </div>
  
  <div class="headerusermenu">
    <div class="dropdown">
      <ul>
        <% if signed_in? %>
          <%=image_tag @current_user.image_url, class:"headerusericon"%>
          <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            <%= @current_user.nickname + 'さん'%>
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu right" aria-labelledby="dropdownMenu1">
            <li><%= link_to 'プロフィール', current_user %></li>
            <li><%= link_to 'マイページ', current_user %></li>
            <li><%= link_to '投稿する', current_user %></li>
            <li><%= link_to 'ホーム', current_user %></li>
            <li class="divider"></li>
            <li><%= link_to 'ログアウト', signout_path, method: :delete %></li>
          </ul>
        <% else %>
          <%=image_tag "hito2.png", class:"headerusericon"%>
          <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            <%= 'ゲストさん'%>
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu right" aria-labelledby="dropdownMenu1">
            <li><%= link_to 'ログイン', signin_path %></li>
            <li><%= link_to 'アカウント作成', signup_path %></li>
            <li class="divider"></li>
            <li><%= link_to 'ホーム', signin_path %></li>
          </ul>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<hr>

<div class="wrapper">
<%= yield %>
</div>

</body>
</html>

app/views/users/edit.html.erb
<h2>アカウント編集</h2>

<%= form_for(@user) do |f| %>

  <div class="form-group">
      <%= f.label :nickname, 'ニックネーム' %>
      <%= f.text_field :nickname, class:"form-control input-sm" %>
    </div>
    <div class="form-group">
      <%= f.label :email, 'メールアドレス' %>
      <%= f.text_field :email, class:"form-control input-sm" %>
    </div>
    <div class="form-group">
      <%= f.label :age, '年齢' %>
      <%= f.text_field :age, class:"form-control input-sm" %>
    </div>
    <div class="form-group">
      <%= f.label :sex, '性別' %>
      <%= f.select(:sex, [['男', 1], ['女', 2]]) %>
    </div>
    <div class="form-group">
      <%= f.label :password, 'パスワード' %>
      <%= f.password_field :password, class:"form-control input-sm" %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, 'パスワード確認' %>
      <%= f.password_field :password_confirmation, class:"form-control input-sm"%>
    </div>
    <div class="form-group">
      <%= f.label :image, 'プロフィール画像' %>
      <%= f.file_field :image %>
    </div>

  <%= f.submit 'アカウントを編集する', class: 'btn btn-primary' %>

<% end %>

app/views/users/index.html.erb
<h2>ユーザ一覧</h2>

<ul>
  <% @users.each do |user| %>
  <li><%= link_to user.email, user %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h2>アカウント作成</h2>

<%= form_for(@user) do |f| %>

    <div class="form-group">
      <%= f.label :nickname, 'ニックネーム' %>
      <%= f.text_field :nickname, class:"form-control input-sm" %>
    </div>
    <div class="form-group">
      <%= f.label :email, 'メールアドレス' %>
      <%= f.text_field :email, class:"form-control input-sm" %>
    </div>
    <div class="form-group">
      <%= f.label :age, '年齢' %>
      <%= f.text_field :age, class:"form-control input-sm" %>
    </div>
    <div class="form-group">
      <%= f.label :sex, '性別' %>
      <%= f.select(:sex, [['男', 1], ['女', 2]]) %>
    </div>
    <div class="form-group">
      <%= f.label :password, 'パスワード' %>
      <%= f.password_field :password, class:"form-control input-sm" %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, 'パスワード確認' %>
      <%= f.password_field :password_confirmation, class:"form-control input-sm"%>
    </div>
    <div class="form-group">
      <%= f.label :image, 'プロフィール画像' %>
      <%= f.file_field :image %>
    </div>

  <%= f.submit 'アカウントを作成する', class: 'btn btn-primary' %>

<% end %>

app/views/users/show.html.erb
<h2>ユーザー情報</h2>

<table>
  <p>プロフィール写真<br>
  <%= image_tag @user.image_url %></p>
  <tr>
    <th>ニックネーム</th>
    <td><%= @user.nickname %></td>
  </tr>
  <tr>
    <th>メールアドレス</th>
    <td><%= @user.email %></td>
  </tr>
  <tr>
    <th>性別</th>
    <td><%= @user.sex_i18n %></td>
  </tr>
  <tr>
    <th>年齢</th>
    <td><%= @user.age %></td>
  </tr>
</table>

<% if current_user?(@user) %>
<p><%= link_to '編集', edit_user_path, class: 'btn btn-primary' %></p>
<% end %>